### ISSUE TITLE
Rating System

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#14]
**What's required:**
Rating system -> Average Box rating - input, calculate, output.

**Conditions:**
1. A user can only rate the machine once he/she has submitted both the flags for it.

**How:**
We can have a Rating model representing a one-to-many relationship between **1** machine and  **N** users ratings.

**Comment by payal-98** [comment]
Can I work on this?

**Comment by Eshaan7** [comment]
We need to resolve #1, then this.

**Comment by payal-98** [comment]
@Eshaan7  shifting of json object to sql database?

**Comment by Eshaan7** [comment]
^Sorry for late response. Yes. We need to move the JSON object. Please see [this comment](https://github.com/abs0lut3pwn4g3/RTB-CTF-Framework/issues/1#issuecomment-590351122).

**Comment by Eshaan7** [comment]
> @Eshaan7 shifting of json object to sql database?

Yes. Please see Issue #28.

**Comment by svensevenslow** [comment]
Can I work on this issue?
Also can you please specify what all fields you need in Rating Model
