### ISSUE TITLE
Adding a "Deploy to Heroku" button.

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#15]
**What's required:**:
 Adding a `Deploy to Heroku` button. 

**How:**
https://devcenter.heroku.com/articles/heroku-button

**Comment by svensevenslow** [comment]
Hi! I'd like to work on this.

**Comment by sammy1997** [comment]
@svensevenslow Any progress on this issue?

**Comment by svensevenslow** [comment]
@sammy1997 working on it right now. I though contributions started from March 1st?

**Comment by svensevenslow** [comment]
Hi! So for the current directory structure it is not possible to add a deploy to Heroku button. It will work only if the code to be deployed is not in a subdirectory(src here) but in the root directory. I have run both the scenarios for your reference in a test repository. You can refer to the documentation has well where this is specified https://devcenter.heroku.com/articles/heroku-button#requirements

Test Repository
Case 1: When code deployed from root directory - Heroku Button works correctly
Code : https://github.com/svensevenslow/vehichle-carbon-emission-backend/commit/9648bb76e7bfc80f977359501f1ae905360f42be
Heroku Button: https://github.com/svensevenslow/vehichle-carbon-emission-backend/tree/testHerokuButton

Case 2: When code deployed from a sub directory - Heroku button does not work
Code : https://github.com/svensevenslow/vehichle-carbon-emission-backend/commit/45b263e6412526747c0aae261d8bdcca85cffedd
Heroku Button: https://github.com/svensevenslow/vehichle-carbon-emission-backend/tree/testButton

You can see the same issue is occurring for CTF code
Code: https://github.com/svensevenslow/RTB-CTF-Framework/commit/db6aa0c9c8d6f07b97065a1406805edefa55b45e
Heroku Button: https://github.com/svensevenslow/RTB-CTF-Framework/tree/Issue%2315#deployment-using-heroku

Please let me know how you want me to proceed further @Eshaan7  @sammy1997

**Comment by Eshaan7** [comment]
Hi, @svensevenslow. Great work, and thank you for providing a clear and concise report. I researched a bit about this and yes, it's not possible to make a deploy button to deploy from subdirectory, but what we can do is make our application deploy-able from the root directory.

Please refer to [here](https://stackoverflow.com/a/43771872) stackoverflow answer on how we can make our app deploy-able from root.

Also, in the `app.json`, you are missing some fields such as addons, scripts.

**Comment by svensevenslow** [comment]
Hi! I have opened a PR for this issue. Please have a look [here](https://github.com/abs0lut3pwn4g3/RTB-CTF-Framework/pull/22)

**Comment by Eshaan7** [comment]
Thank you, @svensevenslow. I have merged your PR and closed this issue.
