### ISSUE TITLE
"Admin Controls" - Dark theme

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#16]
Dark theme for `admin controls`.
Related to Issues: #55, #36.
Tip: (maybe) need to download templates from the flask-admin repo, make changes, and extend them

**Comment by adityabisoi** [comment]
@Eshaan7 I want to work on this. Please assign me. Thanks.

**Comment by sammy1997** [comment]
@adityabisoi I think it will be better if you work on 1 issue at a time! I see that you have also expressed your interest in the linting issue( #18 ). Please let us know which one you want to work on first!

**Comment by adityabisoi** [comment]
Yes, @sammy1997 I want to work on this issue. I just wanted to know a little more detail about issue #18. However, I would like to work on this issue first.

**Comment by ranjal007** [comment]
I need to work on this issue. Please assign it to me.

**Comment by meghaa105** [comment]
Is this issue closed , I would like to work on it

**Comment by meghaa105** [comment]
Thank you , can you please elaborate the exact requirements?

**Comment by Eshaan7** [comment]
Go to the [live demo](rtblivedemo.herokuapp.com/) and see the admin controls. We need that in Dark theme to match the rest of the web app's UI.

**Comment by meghaa105** [comment]
Okay
