### ISSUE TITLE
Support for `n` number of boxes

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#17]
**Prerequisite:**
Issue #28. (Closed and PR Merged)

**What's required:**
Support for `n` number of boxes

**Additional Context:**
1. Create a Many to Many Relationship between Score and Machine.
2. Display the list of all available boxes in an accordion view.
3. Changes in `/validateUser(Root)Hash` and related forms.
4. Changes in route management.
 
**PS:**
Will need to make changes everywhere in the codebase and do rigorous testing.

**Comment by Eshaan7** [comment]
@svensevenslow assigned to you.

**Comment by svensevenslow** [comment]
@Eshaan7  I'll start with the front end part first. So let me know how you want this part done. I mean incorporate the  accordian view for the boxes in which html page/create a fresh page, if you could clarify things along  these lines and anything else want done.
