### ISSUE TITLE
CI, Linting, Formatting

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#18]
Adding a linting/formatting spec for incoming PRs.

**Comment by adityabisoi** [comment]
@Eshaan7 can you please provide some details ?

**Comment by illseption** [comment]
Hi! I'm interested in working on this issue. Can I be assigned?

**Comment by sammy1997** [comment]
@Eshaan7 I think you can assign this one too @illseption He discussed the issue with me on Slack.

**Comment by illseption** [comment]
Hi! I've opened a PR https://github.com/abs0lut3pwn4g3/RTB-CTF-Framework/pull/24 for this issue. Please have a look
