### ISSUE TITLE
Moving organization details to footer.

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#19]
**What's required:**
Moving the sidebar displaying organization details to a footer element.

**How**:
Make changes in the `layout.html` file. 
A simple and neat dark template would do.

**Comment by bhavyasinghal06** [comment]
I have selected as GSSoC'20 participant and would like to resolve this issue.

**Comment by Eshaan7** [comment]
Hi, @bhavyasinghal06. I would like to see something like the footer in this website: http://artemsheludko.com/galada/

**Comment by bhavyasinghal06** [comment]
Hi, Can you review it [here](https://user-images.githubusercontent.com/54326770/75272048-3be22f00-5823-11ea-83d4-ac6ac584a77e.png)

**Comment by Eshaan7** [comment]
Hi, Bhavya.  Nice effort. Could you please make it more like in the above link ?

**Comment by bhavyasinghal06** [comment]
Okay

**Comment by bhavyasinghal06** [comment]
I have added a scroll up button on the footer site. On pressing it the page will scroll up to top and colour of the button also changes. Also added a horizontal line as in the mentioned website.
Review [here](https://user-images.githubusercontent.com/54326770/75286213-1dd5f800-583e-11ea-8437-34c5bd45716b.png)

**Comment by bhavyasinghal06** [comment]
I have added a scroll up button on the footer site. On pressing it the page will scroll up to top and colour of the button also changes. Also added a horizontal line as in the mentioned website.
Review [here](https://user-images.githubusercontent.com/54326770/75287301-229bab80-5840-11ea-96ca-5edee2c2690e.png)

**Comment by Eshaan7** [comment]
Hi. It still needs some polishing and I saw the commit you made, you have seem to hard-coded alot of CSS. This can break the website and also it's not responsive and would break in mobile view. There's hardly any need for custom CSS, please try to use bootstrap as it's already included. Thank you.

**Comment by bhavyasinghal06** [comment]
I haven't used  "ion ion-ios-arrow-up" class.I have used button onclick="topFunction()" id="myBtn".I haven't push the changes after adding more features yesterday.

**Comment by bhavyasinghal06** [comment]
Okay,I will use bootstrap and custom CSS.

**Comment by sammy1997** [comment]
@bhavyasinghal06 Any updates on this? Are you still working on it?

**Comment by bhavyasinghal06** [comment]
My exams are going on. I will let you know after some days.
