### ISSUE TITLE
generation of hash  and comparison

### ISSUE THREAD

**Issue by shvamabps** [abs0lut3pwn4g3/RTB-CTF-Framework#21]
Hash should be provided to user at the time of user .
Also the root hash should be already inserted there so that the extra efforts are reduced. 
root hash has to be predefined there already 
and if the condition meets then boom the box is available
and what one can do is choose which box is required or can have a random generation of box for every user
and the difficulty can also be chosen by the user. In that a single table can be managed for hash box type and difficulty level

**Comment by sammy1997** [comment]
@Eshaan7 This issue has not been labeled

**Comment by Eshaan7** [comment]
@shvamabps Sorry, but it feels like you are not able to understand the purpose of this project, how a CTF works and how a player gets his hands on the hash plus why we are providing the flexibility to have the admin user decide how he wants the hashes. Please ping me on slack and I will try to clear your doubts.  But for now I am closing this issue and marking it invalid.
