### ISSUE TITLE
Request to contribute.

### ISSUE THREAD

**Issue by manan2002** [abs0lut3pwn4g3/RTB-CTF-Framework#27]
Hello! 
I just got to know about GirlScript Summer of Code, then I realised it was too late to register.
I found your repo from their project site and would love to contribute. Flask is my core skill. Let me know with whatever I can help with.

**Comment by sammy1997** [comment]
Hey! Please close this issue and join our slack channel. @Eshaan7

**Comment by manan2002** [comment]
Hi, where can I find the link to the channel?

**Comment by Eshaan7** [comment]
Hi, @manan2002. While it's too late for you to register as a GSSoC participant, we are always looking for contributors. So pick any issue you like, and work on it.

PS - The slack channel is dedicated for GSSoC participants so you cannot be added to it. So if you have any queries, drop me a DM on: https://twitter.com/mask0fmydisguis
