### ISSUE TITLE
Refactor Box object in config.py to Machine model in database

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#28]
Currently, the machine details are stored in a JSON object  (`box`) in config.py file.

What's required:
Need to shift this into a Machine model in the SQL database (via SQLAlchemy model)
This will also enable support for multiple machines as described in issue #17.
Afterwards, we can create a rating system as described in issue #14.

**Comment by svensevenslow** [comment]
Hi! Can I work on this?

**Comment by Eshaan7** [comment]
Yes. I have assigned you. Do remember that: You will need to make changes everywhere in the code and the templates, `create_db.py` as well. Also, would need to change the `Score` model to accommodate the new `Machine` model. In the `Score` model, we will need to add a foreign key to the machine ID. 

Also, in the `Machine` model, please have these necessary fields: 
`id`:int, `name`:string, `user_hash`:string, `root_hash`:string, `user_points`:int, `root_points`:int, `os`:string

PS - If you are able to do this, then #17 should be quite easy. So it's a two for one deal. :)

**Comment by svensevenslow** [comment]
Thanks for the explanation. I'll get back to you if I have any queries.

**Comment by svensevenslow** [comment]
Hi! I have opened a [PR](https://github.com/abs0lut3pwn4g3/RTB-CTF-Framework/pull/43). Let me know what you think
