### ISSUE TITLE
Freeze Scoreboard automatically

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#3]
Freezing scoreboard once the CTF is ended. According to the running time provided in config.py

Idea: might be possible using `datetime` module

**Comment by svensevenslow** [comment]
Hi! I'd like to work on this. Can you assign me this issue? Also what is the difficulty tag of this issue?

**Comment by svensevenslow** [comment]
Hi! I've opened a [PR](https://github.com/abs0lut3pwn4g3/RTB-CTF-Framework/pull/25). Please have a look.
