### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [abs0lut3pwn4g3/RTB-CTF-Framework#35]
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@Eshaan7   As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project. Using [this]( https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) as a reference. 

**Additional context**
### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by saloniankita23** [comment]
Has this issue been solved ?
If not I'd like to work on it.

**Comment by Eshaan7** [comment]
Please add something along the lines of "As contributors and maintainers of the RTB-CTF-Framework project, and in the interest of fostering an open and welcoming community...."
