### ISSUE TITLE
Create CONTRIBUTE.md

### ISSUE THREAD

**Issue by vipuldcoder** [abs0lut3pwn4g3/RTB-CTF-Framework#37]
Is your feature request related to a problem? Please describe.
This is feature which help new contributor to understand how they can contribute project and how we can help this project more effect and do understand what this project really is and how we can get started. Let's get started with making this project more better 👍

Describe the solution you'd like
Build a Document CONTRIBUTE.md that help everyone to understand what this project is and how the collaborator get started with this and understand what the current project status and Where they need to take.

**Comment by Eshaan7** [comment]
Hi. Thanks for the suggestion. That can be helpful. However, I don't understand what more could be added. We already have a [To-do](eshaan7  8:54 PM
The integrations I have listed, in my opinion, are challenging to me. If time allows, I will also work on some external services such as FireHOL, Malpedia, URLHaus. But I think it's better for me to not commit more than I can take on and it'd be better to finish early on my weekly goals than late
new messages
matteo.lodi  8:57 PM
yep they are. Consider that if you get accepted and you find some problems during the development I am here to help you and we can discuss and change the objectives if needed) list.

**Comment by Eshaan7** [comment]
Hi. Thanks for the suggestion. That can be helpful. However, I don't understand what more could be added. We already have a [To-do](https://github.com/abs0lut3pwn4g3/RTB-CTF-Framework#to-do) list.

**Comment by Eshaan7** [comment]
@vipuldcoder, If you have any explicit suggestions on things that could be added to the README, please ping me on the slack channel.
