### ISSUE TITLE
Improve Code Quality of Project [LGTM]

### ISSUE THREAD

**Issue by Eshaan7** [abs0lut3pwn4g3/RTB-CTF-Framework#47]
**Describe the bug**
Improve Code Quality of Project

**Expected behavior**
Atleast bring it up to B

**Additional context**
Research on how to improve code quality and improve it too.

PS: If you feel any alert in the LGTM report is of breaking nature, DM me about it on slack.

**Comment by diru1100** [comment]
Hey @Eshaan7 , I would like to work on this.

**Comment by Eshaan7** [comment]
I am taking you off from this issue due to some conflicts with Travis integration, @diru1100.

**Comment by Pihu1998** [comment]
Hi @Eshaan7 . Is this issue up for grabs? Can I work on this issue?

**Comment by Eshaan7** [comment]
> Hi @Eshaan7 . Is this issue up for grabs? Can I work on this issue?

Not anymore, sorry. Forgot to close this. The code quality is at A now.
