### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by Demaz93** [abs0lut3pwn4g3/RTB-CTF-Framework#65]
**Is your feature request related to a problem?**
For private usage like universities or organizations it could be hard ask to everyone to perform registration.

**Describe the solution you'd like**
Could be awesome add the possibility to disable registration and add only ldap log-in using accounts available on university or organization infrastructure.

**Comment by Eshaan7** [comment]
Hi. Thanks for your interest. Do you have an example on how this could be useful ? To be clear, it seems like over-complicating. At the moment, one can create multiple admin users from the ORM or CLI (complicated but that is done to keep it secure). Adding a separate auth mechanism will only introduce delays and errors and ultimately increases attack surface and is directly against the purpose of this project i.e. keeping the framework easy to deploy, lightweight, and features strictly what is necessary.
